apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
    push: false
    concurrency: 0
  artifacts:

    - image: backend
      context: code/golang-echo-realworld-example-app
    - image: frontend
      context: code/vue-realworld-example-app

deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - bonus/local-deploy/**