apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
        - name: frontend
          image: 952034392840.dkr.ecr.eu-west-1.amazonaws.com/frontend
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - name: frontend-port
              containerPort: 80
          readinessProbe:
            tcpSocket:
              port: frontend-port
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 4
          livenessProbe:
            tcpSocket:
              port: frontend-port
            periodSeconds: 15
            failureThreshold: 4