apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: backend
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - name: backend-port
              containerPort: 8585
          readinessProbe:
            tcpSocket:
              port: backend-port
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 8
          livenessProbe:
            tcpSocket:
              port: backend-port
            periodSeconds: 15
            failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 8585
      targetPort: 8585
      protocol: TCP